/// <reference lib="webworker" />

import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all assets generated by build process
precacheAndRoute(self.__WB_MANIFEST);

// Handle navigation requests - fallback to index.html for SPA routing
const navigationHandler = createHandlerBoundToURL('/Armaan-Tech-Tips/');
const navigationRoute = new NavigationRoute(navigationHandler, {
  allowlist: [/^\/Armaan-Tech-Tips\/.*$/],
  denylist: [/\/api\/.*$/],
});
registerRoute(navigationRoute);

// Cache static assets (CSS, JS, images)
registerRoute(
  /\.(?:css|js|png|jpg|jpeg|svg|gif|webp|woff|woff2)$/,
  new StaleWhileRevalidate({
    cacheName: 'static-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  })
);

// Handle install prompt
self.addEventListener('beforeinstallprompt', (event: Event) => {
  // Store the event for later use in the main app
  (self as any).installPromptEvent = event;
});

// Handle app installed
self.addEventListener('appinstalled', () => {
  // Notify the main app that installation is complete
  console.log('PWA installed successfully');
});

// Skip waiting and activate new service worker immediately
self.addEventListener('message', (event: ExtendableMessageEvent) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    (self as any).skipWaiting();
  }
});
